name: Auto Crawl

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests # 或者其他你的脚本所需要的依赖

      - name: Run crawler
        run: python crawler.py

      - name: Commit and push changes
        run: |
          git config --global user.email "5020559@gmail.com"
          git config --global user.name "Vincent550102"
          git add .
          git commit -m "Update content" -a || echo "No changes to commit"
          git push
